from pathlib import Path
import csv,json,statistics,math,hashlib
D=Path('/mnt/r/plastchem-euler/post1111-octanol-2026-09-15');E=D/'opera-extension';E.mkdir(exist_ok=True)
rows=list(csv.DictReader(Path('/mnt/r/plastchem-euler/post1096-octanol-2026-09-15/opera-extension/cumulative-parity.csv').open()));old={r['input_inchikey'] for r in rows};added=[];audit={r['inchikey']:r for r in json.loads((D/'numerical-audit.json').read_text())['rows']}
for r in csv.DictReader((D/'opera-experimental-reference-candidates.csv').open()):
 k=r['input_inchikey']
 if k in old:continue
 p=D/'octanol'/f'{k}.json';assert audit[k]['status']=='passed' and hashlib.sha256(p.read_bytes()).hexdigest()==audit[k]['result_sha256'];v=json.loads(p.read_text());r.update(predicted_logKow=v['prediction']['log10_K_concentration']);r['residual_predicted_minus_measured']=r['predicted_logKow']-float(r['measured_logKow']);added.append(r)
rows+=added;fields=list(dict.fromkeys(k for r in rows for k in r))
with (E/'cumulative-parity.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
x=[float(r['measured_logKow']) for r in rows];y=[float(r['predicted_logKow']) for r in rows];e=[b-a for a,b in zip(x,y)];mx=statistics.mean(x);my=statistics.mean(y);slope=sum((a-mx)*(b-my) for a,b in zip(x,y))/sum((a-mx)**2 for a in x)
s={'n':len(rows),'unique_connectivity':len({r['input_inchikey'].split('-')[0] for r in rows}),'prediction_denominator':1138,'MAE':statistics.mean(map(abs,e)),'RMSE':math.sqrt(statistics.mean(v*v for v in e)),'bias':statistics.mean(e),'slope':slope,'intercept':my-slope*mx,'added':added,'selection':'Earlier 59 references unchanged. Added qualified OPERA observed value; no recalibration.'};(E/'experimental-statistics.json').write_text(json.dumps(s,indent=2)+'\n');(E/'REPORT.md').write_text(f"# OPERA extension\n\nThe 27-molecule batch matched four OPERA experimental observations by connectivity and CAS. Previously selected references are retained; newly matched entries are added. Cumulative n={s['n']} ({s['unique_connectivity']} connectivity skeletons) among 1,138 audited octanol predictions: MAE {s['MAE']:.6f}, RMSE {s['RMSE']:.6f}, bias {s['bias']:+.6f}, slope {s['slope']:.6f}, intercept {s['intercept']:.6f}. No recalibration. Earlier comparisons remain unchanged. Per-row citations are in cumulative-parity.csv; the source digest and experimental qualification are in ../opera-match-summary.json. This is incomplete measured coverage, and the campaign and full solvent panel remain pending. Xylene and didecyl phthalate remain owner questions.\n\nReproduce from /home/aaltamimi2/plastchem-euler with `python3 scripts/match_post1111_opera.py` and `python3 scripts/extend_post1111_opera.py`.\n");print(json.dumps(s,indent=2))
