"""Render the final Phase 1 report only after every selected task has a disposition."""
import csv,json,collections
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];P=ROOT/'state/pilot-v1';R=ROOT/'reports/pilot-v1'
a=json.loads((R/'analysis.json').read_text());v=json.loads((P/'verified-state.json').read_text());snap=json.loads((P/'latest-snapshot.json').read_text())
assert not snap['squeue'].strip(),'Pilot is still queued/running; refuse a final report'
assert v['counts']['running']==0 and v['counts']['not_yet_run']==0 and v['counts'].get('awaiting_verification',0)==0,'Missing terminal dispositions'
rows=list(csv.DictReader((R/'molecules.csv').open()));models=', '.join(a['cpu_models'])
executed=sum(bool(r['cpu_model']) for r in rows)
lines=['# Phase 1 pilot — final report and stop','',f"Array **{snap['array_job_id']}**, deterministic name `contam-p1-milan-v1`. Partition **research**, constraint **milan&cpu**, euler09/euler10 excluded. One array, concurrency cap **16**, one CPU, 4G RAM, 12-hour limit per task. Measured compute CPU model(s): **{models}**. No Phase 2 submission.",'',
 f"Pilot disposition: **{a['counts']['converged']}/56 converged and identity-verified, {a['counts']['failed']}/56 failed, {a['counts']['not_yet_run']}/56 not yet run**; {a['counts']['running']}/56 running. A preflight input-representation failure is counted as failed, even though DFT did not execute for it. See the complete 56-row `molecules.csv` for every identity, timing, node, CPU model, memory measurement, returned-file size, and residual.",'',
f"DFT execution coverage: **{executed}/56 executed, {56-executed}/56 never executed**. Normally completed OPT + COSMORS: **{a['fit_normally_completed_dft']}/56**; chemical acceptance is reported separately above.",'',
'## Selection and execution','',
'56 unique CHNO InChIKeys were chosen deliberately: seven molecules per atom-count band (15–22, 23–30, 31–38, 39–46, 47–54, 55–62, 63–70, 71–80), with farthest-point coverage in atom count, heavy atoms, rotatable bonds, rings, aromatic atoms, nitrogen and oxygen. DEP, DBP, BBP, DEHP and dibenzyl phthalate were forced into the selection, along with the 15/80 endpoints. There were no MMFF availability, radical, or SMILES-key eligibility exclusions within this range. Preparation used the reference ETKDGv3/MMFF ranking settings: 300 candidate embeddings, seed 12345, 0.5 Å RMSD pruning, 2,000 MMFF iterations. Exactly one lowest-energy converged conformer per molecule was staged for DFT.','',
'The frozen ORCA recipe was unchanged: serial, no `%pal`, `%maxcore 1500`, neutral singlet; OPT BP86/def2-TZVP(-f)/TightSCF followed by COSMORS(Water), whose generated solute SP uses BP86/def2-TZVPD. ORCA version/GIT, exact input decks and digests, node, CPU model/flags and elapsed times were recorded per executed task. The 56 staged XYZ digests and manifest were verified before submission.','',
'One entry, benz[a]anthracene-d12 (`DXBHBZVCASKNBY-AQZSQYOVSA-N`, task 42), was confirmed pending and cancelled before DFT because plain XYZ had erased its isotope labels. It was not replaced or retried. An isotope-safe representation must be resolved before a later full campaign includes such inputs.','',
'## Timings, scaling and residuals','']
if 'fit' in a:
 f=a['fit'];b=f['bootstrap_cpu_hours_p05_p50_p95'];archive=f['archive_bytes_bootstrap_p05_p50_p95']
 lines += [f"For **{models} / research / Milan**, the normally completed DFT timing fit is `mean wall seconds = exp({f['intercept']:.6f}) × atoms^{f['exponent']:.6f} × {f['residual_smearing']:.6f}`. It models measured process wall time for OPT + COSMORS, including launch/I/O overhead; it is not a pure CPU-clock benchmark. Log-space RMSE: **{f['log_rmse']:.3f}**. Observed/predicted wall ratios at the 10th/50th/90th percentiles: **"+'/'.join(f'{x:.2f}' for x in f['observed_to_predicted_ratio_p10_p50_p90'])+'**. Each molecule’s signed seconds residual and ratio are in the CSV.','',
'![Wall time and residuals](wall-and-residuals.png)','',
 f"Applying the fitted completed-DFT cost model to all **5,833** pinned CHNO structures gives **{f['campaign_cpu_hours']:,.0f} serial CPU-hours**. The within-stratum bootstrap sensitivity range (5th–95th percentiles; 2,000 resamples) is **{b[0]:,.0f}–{b[2]:,.0f} CPU-hours**, median **{b[1]:,.0f}**. At an illustrative 16-way concurrency with uninterrupted utilisation, this range corresponds to **{b[0]/16/24:.1f}–{b[2]/16/24:.1f} days**, before queue delays or retry work. This is a scenario calculation, not approval of full-campaign concurrency.",'',
'The resampling range is conditional model uncertainty, not a coverage-guaranteed confidence interval: this was a deliberate diversity sample, not a random sample. Failures, chemistry-dependent stalls, and later queue load add uncertainty not captured by a smooth atom-count curve. No time-truncated run is silently treated as a cheap success. Failure/time-limit observations and elapsed lower bounds are retained below and in the CSV.','',
 f"The population includes **{a['extrapolation_below_15']} structures below 15 atoms and {a['extrapolation_above_80']} above 80 atoms**; costs for those are extrapolations. A full-campaign decision should review those tails and all failure modes instead of treating the fitted mean as a guarantee.",'',
 f"The measured returned-byte scaling projects **{archive[1]/1e9:.2f} GB**, with a conditional bootstrap range **{archive[0]/1e9:.2f}–{archive[2]/1e9:.2f} GB**, for the five-file bundles of 5,833 successful results. This replaces the earlier anchor-only sizing hypothesis; full scratch remains on Euler and is outside this return estimate.",'']
else:lines += ['Too few normally completed DFT timings for a defensible runtime or archive projection; no fit or campaign estimate was fabricated.','']
lines+=['The timing fit includes normally completed DFT runs whose chemical identity remains unresolved, because their measured atom counts and consumed computation time are still valid workload observations. This does not promote their surfaces to accepted chemical results. SCF/geometry failures and timeouts are excluded from the completed-run fit and retained in the separate all-attempt budget below.','']
if 'all_attempt_budget' in a:
 ab=a['all_attempt_budget'];q=ab['bootstrap_cpu_hours_p05_p50_p95']
 lines += [f"**Failure-inclusive one-attempt budget:** **{ab['campaign_cpu_hours']:,.0f} CPU-hours** for 5,833 attempts, conditional bootstrap sensitivity range **{q[0]:,.0f}–{q[2]:,.0f} CPU-hours**. This uses all {ab['attempts']} executed terminal attempts, including elapsed cost of failed/limited runs, so costly failures do not vanish from the resource budget. The observed pilot consumed {ab['observed_total_attempt_hours']:.2f} attempt-hours. It excludes retry work and does not promise 5,833 successful surfaces. Timed-out completion costs remain lower bounds.",'']
lines+=['## Four workstation anchors','',
'The comparison below uses the `TOTAL RUN TIME` lines from both architectures for consistency, rather than mixing those with process-launch wall time. Correction C-1 confirms the historical workstation CPU as Intel Core i7-13700 (Raptor Lake), not Broadwell; the Euler login node alone is Broadwell. The table reports cross-machine ratios for AMD EPYC 7763 (Milan) versus Intel Core i7-13700. Historical anchor times are not used to fit the campaign estimate. Initial conformers were regenerated; DEHP’s pinned input also leaves stereo unspecified, while the reference implementation names a specified stereoisomer. Thus these are workload timing comparisons, not controlled CPU-only benchmarks.','',
'| Anchor | i7-13700 ORCA total (s) | EPYC 7763 ORCA total (s) | EPYC 7763/i7-13700 | Status |',
'| --- | ---: | ---: | ---: | --- |']
for r in sorted(a['anchors'],key=lambda r:['DEP','DBP','BBP','DEHP'].index(r['selection_role'])):
 t=r['orca_internal_total_seconds'];ratio=r['milan_over_i7_13700_ratio']
 lines.append(f"| {r['selection_role']} | {r['workstation_total_seconds']:.3f} | {t:.3f}"+f" | {ratio:.3f} | {r['status']} |" if t is not None else f"| {r['selection_role']} | {r['workstation_total_seconds']:.3f} | unavailable | unavailable | {r['status']} |")
lines+=['','The historical Intel Core i7-13700 optimisation cycle counts were DEP 8, DBP 17, BBP 32 and DEHP 25. BBP therefore needed nearly twice the geometry steps of DBP; the runtime difference was not just a smooth atom-count effect. Pilot geometry-cycle counts are included in the CSV alongside wall times.','',
'The additional aromatic ester, dibenzyl phthalate, is identified in the CSV by `additional_aromatic_ester_dibenzyl_phthalate`.','',
'## RAM, failures, identity and return records','']
ester=next(r for r in rows if r['selection_role']=='additional_aromatic_ester_dibenzyl_phthalate')
if ester.get('residual_seconds'):
 at=lines.index('## RAM, failures, identity and return records')
 lines[at:at]=[f"On {models}, dibenzyl phthalate ({ester['atoms']} atoms) took **{float(ester['total_orca_wall_seconds'])/60:.2f} minutes**, a **+{float(ester['residual_seconds'])/60:.2f}-minute residual** and **{float(ester['observed_predicted_ratio']):.2f}×** the size-fit mean. This is a second aromatic ester with appreciable excess cost.",'']
rss=[float(r['maxrss_kib']) for r in rows if r['maxrss_kib']]
if rss:lines.append(f"Largest recorded Slurm batch-step MaxRSS: **{max(rss)/1024:.1f} MiB**, with measurements available for **{len(rss)}/{executed} executed tasks**. All requests were 4G. Per-molecule high-water values are in the CSV; missing scheduler measurements remain blank.")
bundle_bytes=sorted(int(r['returned_bytes']) for r in rows if r['dft_converged']=='True' and r['returned_bytes'])
if bundle_bytes:lines.extend(['',f"Measured five-file bundle sizes span **{min(bundle_bytes):,}–{max(bundle_bytes):,} bytes** across {len(bundle_bytes)} normally completed DFT runs; total **{sum(bundle_bytes):,} bytes**. The CSV gives each exact size, including the separate preflight diagnostic record."])
lines+=['',f"Executed runs without normal OPT + COSMORS completion: **{executed-a['fit_normally_completed_dft']}/{executed}**. Failure modes across the 56 selected records: "+'; '.join(f"`{mode}`: {count}/56" for mode,count in collections.Counter(r['failure_mode'] for r in a['failures']).items())+'.','',f"Identity policy used: `{v['identity_policy']['mode']}`. Both RDKit and Open Babel geometry-perception observations are retained where obtained; no unresolved identity is relabelled as verified. Surfaces and exact input decks were digest-checked on return.",'']
for r in a['failures']:lines.append(f"- `{r['inchikey']}` — {r['name']}; **{r['failure_mode']}**; {r['error'] or 'see preflight exception record'}.")
if not a['failures']:lines.append('No failures were observed in this pilot.')
lines+=['',
'Per InChIKey, returned artifacts are `surface.orcacosmo`, `result.json`, `opt.inp`, `cosmo.inp`, and `optimized.xyz` under `/mnt/r/plastchem-euler/results/<InChIKey>/`. Failed tasks return the available diagnostic record/decks without a fabricated surface. Exact returned bytes per molecule are in the CSV. Transfer uses the required multiplexed scp connection; local root space is checked before retrieval. Full scratch/stdout remain under `~/plastchem-euler/pilot-v1/runs/<InChIKey>/` on Euler.','',
'Full-corpus representation audit: **9/5,833** pinned structures contain isotope labels that plain XYZ cannot preserve. One additional entry, carbon monoxide (`UGFAIRIUMAVXCW-UHFFFAOYSA-N`, 2 atoms), lacks MMFF parameters. Neither issue is silently removed from the 5,833 target or replaced with another molecule; both need explicit preparation/identity handling before full-campaign execution. The pilot contains only the one already reported isotope case and no CO. There are no radical structures or SMILES/InChIKey mismatches in the census audit. See `state/pilot-v1/representation-audit.json`.','',
'## Reconciliation and phase gate','',
'Before submission, both squeue and sacct were checked for the deterministic pilot name and were empty. One array receipt was recorded. Final reconciliation by deterministic name, covering the submission date across midnight, is preserved in `logs/pilot-final-name-reconciliation.txt`; the final squeue is empty. The A-1 reconciliation found exactly completed jobs 54150 and 54151; no duplicate diagnostic was submitted. The read-only monitor used a 120-second cadence with failure backoff and the prescribed ControlMaster/ControlPath/ControlPersist settings and exited after all tasks had terminal dispositions. The only later scheduler mutation was cancellation of the documented pending isotope task. No other campaign job was touched.','',
'**Reported and stopped. Phase 2 remains unauthorised.** Retain research/Milan and per-result CPU-model records for any cleared continuation; a change of partition or CPU generation requires matching pilot calibration. Resolve identity/isotope cases before treating the pilot as unqualified full-campaign readiness. Historical anchor provenance was corrected by C-1.']
(R/'REPORT.md').write_text('\n'.join(lines)+'\n')
print(R/'REPORT.md')
