import json
from pathlib import Path
s=json.loads(Path('state/a1-status.json').read_text())
lines=['# Phase 0 / Amendment A-1 — diagnostics passed; report and stop','',
'2026-09-12. The compute-node AVX2 gate is closed for the tested research/Milan target. Exactly two diagnostic jobs were submitted, both completed successfully. No campaign array, campaign job, or Phase 1 pilot was run.','',
'Both jobs ran on **euler145.engr.wisc.edu**, **AMD EPYC 7763 64-Core Processor (Milan)**. The full `/proc/cpuinfo` flags and `lscpu` output were captured. The `avx2` flag was checked before ORCA; the actual ORCA 6.1.1 AVX2 binary then executed both frozen-recipe stages and produced surfaces. Slurm also identifies this node with `amd,epyc,milan,ssd,cpu`.','',
'| Molecule / job | Atoms incl. H | OPT wall (s) | COSMORS wall (s) | Slurm elapsed (s) | Slurm peak RSS (MiB) | Surface bytes | Five-file bundle bytes |',
'| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |']
for key,row in s['diagnostics'].items():
 r=json.loads(Path(f'state/a1-{key}.json').read_text());a=r['slurm_accounting']
 lines.append(f"| {r['input']['name']} / {r['job_id']} | {r['input']['atom_count']} | {r['stages']['opt']['wall_seconds']:.3f} | {r['stages']['cosmo']['wall_seconds']:.3f} | {a['elapsed_seconds']} | {a['maxrss_kib']/1024:.2f} | {r['surface_bytes']:,} | {row['returned_bytes']:,} |")
lines += ['',
'All timings in the table were measured on the AMD EPYC 7763 Milan CPU above; stage wall includes process startup and I/O. Peak RSS is the Slurm batch-step measurement, not the requested allocation. Both jobs have `COMPLETED`, exit `0:0`.','',
'Each job requested **research**, constraint **milan&cpu**, one node, one task, **1 CPU**, **4G memory**, **00:15:00**. Nodes euler09 and euler10 were explicitly excluded. Job 50511 remained running on vanlehn/euler09 at the final queue check; it was not modified. No account argument was needed, confirming the prior entitlement assessment through actual submission.','',
'Water was regenerated using one ETKDGv3 + MMFF94 conformer. Ethanol was selected from the digest-verified CHNO submission set: CAS 64-17-5, PlastChem ID 11245, SMILES CCO. Both inputs use seed 20260912. Exactly one conformer per molecule was passed to DFT. The frozen decks were OPT BP86/def2-TZVP(-f)/TightSCF and COSMORS(Water), neutral singlet, serial, `%maxcore 1500`, no `%pal`. The generated COSMORS solute calculation explicitly used BP86/def2-TZVPD. All parent runs terminated normally, optimisation converged, and ORCA reported **6.1.1 / GIT 487d211c**.','',
'Post-optimisation identities were perceived from the returned XYZ with RDKit and matched the expected InChIKeys. Returned surface and input-deck digests were independently verified locally:','']
for key,row in s['diagnostics'].items():lines.append(f"- `{key}` — surface SHA-256 `{row['surface_sha256']}`.")
lines += ['',
'**Diagnostics: 2/2 converged, 0/2 failed, 0/2 not yet run.** The ethanol result is scoped as an A-1 diagnostic, not silently credited as a completed campaign job. Campaign execution remains 0/5,833; its state remains 0 converged, 0 failed, 5,833 not yet run.','',
'The accepted return path was exercised end to end. Each verified bundle contains exactly `surface.orcacosmo`, `result.json`, `opt.inp`, `cosmo.inp`, and `optimized.xyz` under `/mnt/r/plastchem-euler/results/<InChIKey>/`. Full diagnostic stdout, COSMORS subsidiary outputs, CPU flags, and lscpu evidence are under `/mnt/r/plastchem-euler/diagnostics-a1/evidence/<InChIKey>/`. Scratch remains in the user’s Euler home at `~/plastchem-euler/diagnostics-a1/runs/<InChIKey>/`. Verified local identities/accounting were copied back as `verified-result.json`, preserving the original compute-stage record. Transfers used scp. Local root was checked before retrieval (2.4 GB free); bulk retrieval went directly to R:.','',
'The diagnostic return sizes are measurements, not representative estimates of the 5,833-structure set. The earlier approximately 3.1 GB projection remains only an anchor-based planning hypothesis. Report a new population projection after the cleared pilot provides real sizes.','',
'**Calibration constraint:** use research with the Milan CPU generation for both pilot and campaign if this target is retained; record the exact CPU model for every result. The four workstation anchors and previous login smoke were Intel Broadwell; their times are not interchangeable with Milan, and Genoa is a separate calibration target. If the campaign target changes generation or partition, rerun the pilot calibration on that target. This diagnostic does not establish throughput or safe campaign concurrency.','',
'Reproducible scripts: `scripts/prepare_a1.py`, `scripts/a1_diagnostic.py`, `scripts/a1_diagnostic.sbatch`, `scripts/submit_a1.sh`, `scripts/verify_a1.py`. Input/script provenance: `state/A1-PROVENANCE.sha256`. Records: `state/a1-status.json` and the two `state/a1-<InChIKey>.json` files. Scheduler evidence: `logs/a1-job-allocations.txt`, `logs/a1-final-accounting.txt`. Submission markers and exclusive per-structure attempt locks prevent accidental duplicate submissions or silent reruns.','',
'**Phase 0 complete after A-1. Stopped.** No remaining diagnostic blocker. Phase 1 still requires orchestrator/owner clearance; Phase 2 still requires explicit owner approval.']
Path('reports/PHASE0-A1.md').write_text('\n'.join(lines)+'\n')
Path('PROGRESS.md').write_text('Phase 0 + Amendment A-1 complete; stopped — 2026-09-12.\n\nTwo research/Milan diagnostic jobs completed: 54150 water, 54151 ethanol. Node euler145, AMD EPYC 7763 64-Core Processor; AVX2 flag and real ORCA 6.1.1 / GIT 487d211c execution verified. OPT + COSMORS and post-optimisation identity passed 2/2; failed 0/2. Accepted five-file return bundles verified on R:. Existing vanlehn job 50511 untouched.\n\nNo campaign jobs or Phase 1. Pilot and campaign must share partition and CPU generation; every result pins CPU model. Phase 1 requires clearance.\n\nReport: reports/PHASE0-A1.md. State: state/a1-status.json.\n')
print('\n'.join(lines[:10]))
