"""Render owner options without applying either option or changing campaign state."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
census = json.loads((ROOT / 'state/isotope-census/census.json').read_text())
lines = [
    '# Isotope census and owner policy options', '',
    'Local audit of the five digest-verified pinned files. No cluster command, submission, retry, input edit, or isotope policy selection was performed. The Phase 1 pilot is already complete; this follow-up does not change its 56-molecule denominator or task 42’s reported preflight failure.', '',
    '## Counts', '',
    '| Tier | Unique structures | Isotope-labelled structures | Labelled source rows | Isotopes found | Existing unlabelled parents in same tier |',
    '| --- | ---: | ---: | ---: | --- | ---: |',
]
for tier in ['CHNO', 'heteroatoms', 'Si_B']:
    s = census['summary'][tier]
    labels = ', '.join(f'{label}: {count} structures' for label, count in s['isotope_entry_counts'].items()) or 'None'
    lines.append(f"| {tier} | {s['unique_structures']:,} | {s['labelled_unique_structures']} | {s['labelled_source_rows']} | {labels} | {s['labelled_entries_with_parent_in_same_tier']} |")
lines += [
    '', 'Total: **10/7,792 unique structures**, represented by **10/8,065 source rows**. Nine contain deuterium; one contains three chlorine-36 atoms. No other explicit isotope labels, including carbon-13, nitrogen-15 or oxygen-18, occur in these pinned tiers.', '',
    'Detection used nonzero RDKit atom isotope flags for every source row, cross-checked against bracketed mass-number tokens. Names were not used to decide whether a structure was labelled. Duplicate rows were grouped by the pinned full InChIKey and required to agree on isotope presence and parent key.', '',
    '## Complete candidate mapping', '',
    '| Tier | Source name | Labelled InChIKey | Unlabelled parent InChIKey | Parent in pinned inputs? |',
    '| --- | --- | --- | --- | --- |',
]
for r in census['records']:
    present = f"Yes: {r['parent_names']} ({r['parent_tier']})" if r['parent_present_in_any_tier'] else 'No'
    lines.append(f"| {r['tier']} | {r['name']} | `{r['inchikey']}` | `{r['unlabelled_parent_inchikey']}` | {present} |")
lines += [
    '', 'The [CSV mapping](isotopologue-parent-mapping.csv) also includes labelled and parent SMILES, isotope composition, CAS, source-row count and parent presence. The machine-readable census retains every original source row, isotope atom index, RDKit version and input digest.', '',
    'All **10/10** parent mappings are mechanically constructible. All **9/9 CHNO** parents are already present in CHNO. The **1/1 heteroatom** parent, `WMUBNWIGNSIRDH-UHFFFAOYSA-N`, is absent from all pinned tiers; mapping that entry would require an explicitly derived parent target in a future owner-cleared heteroatom workflow. There are no Si/B mappings and no isotope-to-parent collisions between these ten candidates.', '',
    'Parents were generated by clearing atom isotope flags, removing ordinary explicit hydrogen and cleaning stereo assignments. Every parent passed a canonical SMILES/InChIKey roundtrip and retained the source connectivity block. Source charge, connectivity and non-isotope chemistry were not intentionally changed; isotope-induced stereochemistry must not be carried over as an artificial parent constraint.', '',
    'Two CHNO parents, perylene and dibutyl phthalate, already have identity-verified pilot results. The DEHP parent completed DFT but failed the current strict stereo-identity check; a mapping decision would not resolve or override that separate acceptance failure. The other six CHNO parents were outside the pilot. No result has been reused or attributed to an isotopologue in this audit.', '',
    '## Options for the owner — neither selected', '',
    '**Option A: exclude isotope-labelled entries from the campaign scope as analytical standards.** If the owner adopts this scope rule, retain all source records and mark the labelled keys explicitly excluded, with the policy and reason. Isotope labelling identifies these entries; it does not by itself prove every entry’s use classification.', '',
    '| Tier | Labelled entries excluded | Remaining unique targets |',
    '| --- | ---: | ---: |',
]
for tier in ['CHNO', 'heteroatoms', 'Si_B']:
    s = census['summary'][tier]
    lines.append(f"| {tier} | {s['labelled_unique_structures']} | {s['unlabelled_unique_if_excluding_isotopologues']:,} |")
lines += [
    '| All tiers | 10 | 7,782 |', '',
    'For CHNO, this is **5,824 future unique targets plus 9 explicitly excluded source identities**, not a silent reduction of the pinned 5,833-key set. The original files, row mappings and completed pilot denominator remain intact.', '',
    '**Option B: calculate each unlabelled electronic parent once and retain explicit isotopologue-to-parent attribution.** Under the Born–Oppenheimer electronic model described by the orchestrator, the isotopologue and parent share the equilibrium electronic geometry and COSMO sigma surface; their entry identities differ. This is reuse of an electronic surface, not a direct isotope-specific calculation, and does not claim equality of isotope-dependent vibrational or nuclear-motion properties. Independently run numerical optimisations are still subject to convergence and CPU differences.', '',
    '| Tier | Retained source identities | Distinct electronic targets | Derived parents absent from pinned inputs |',
    '| --- | ---: | ---: | ---: |',
]
for tier in ['CHNO', 'heteroatoms', 'Si_B']:
    s = census['summary'][tier]
    lines.append(f"| {tier} | {s['unique_structures']:,} | {s['distinct_electronic_targets_if_mapping_all']:,} | {len(s['parents_missing_from_same_tier'])} |")
lines += [
    '| All tiers | 7,792 | 7,783 | 1 |', '',
    'For CHNO, this keeps **5,833 source identities backed by 5,824 distinct electronic targets**, because all nine parents already exist. For the parked heteroatom tier, **1,721 source identities still require 1,721 electronic targets**: the isotope-labelled input is replaced at the calculation layer by one otherwise absent parent. These are target counts, not new authorised job counts; completed acceptable parent results would only be reused under an approved provenance policy.', '',
    'A future mapping result should retain `source_inchikey`, `calculation_parent_inchikey`, isotope composition, mapping-policy/version and owner authority, parent input/deck digests, parent surface digest and CPU model, and the actual post-optimisation **parent** InChIKey. It must explicitly identify a mapped electronic result and link the original source rows. Never relabel a parent’s geometry-derived key as the isotope-labelled key, and do not bypass parent convergence or identity validation. The submitted XYZ represents the unlabelled parent.', '',
    'Neither option has been applied. All tiers retain their pinned counts, task 42 remains a reported preflight failure with denominator 56, and Phase 2 remains unauthorised.', '',
    '## Audit-gap attribution and hardware correction', '',
    census['audit_gap_attribution'], '',
    'Correction C-1 is already incorporated in the completed [Phase 1 report](../pilot-v1/REPORT.md): the historical anchors ran on **Intel Core i7-13700 (Raptor Lake)**, while Euler LOGIN is **Xeon E5-2640 v4 (Broadwell)**. Pilot compute ran on **AMD EPYC 7763 (Milan)**. The revised estimate is based solely on the 55 completed Milan DFT timings: one-attempt projection **4,832 CPU-hours**, conditional bootstrap sensitivity band **4,340–5,295 CPU-hours**, excluding retries and with selection/extrapolation limitations stated in that report. EPYC 7763/i7-13700 ORCA wall ratios are **DEP 3.729, DBP 1.954, BBP 1.942, DEHP 4.181**; they are cross-machine workload ratios, not a controlled CPU-only benchmark. No historical estimate was used to fit the revised budget.',
]
(ROOT / 'reports/isotope-census/REPORT.md').write_text('\n'.join(lines) + '\n')
print(ROOT / 'reports/isotope-census/REPORT.md')
